baseURL = "http://45.77.25.204/"
languageCode = "en-us"
title = "Yushi Omote"
theme = "github-style"

[params]
author = "Yushi Omote"
description = "Low level"
github = "yushiomote"
twitter = "ysmoo"
linkedin = "pub/yushi-omote/47/a9a/b59/"
email = "yushiomote@gmail.com"
utterances = "yushiomote.org"
